<select name="calc_shipping_country" id="calc_shipping_country" class="country_to_state country_select" rel="calc_shipping_state">
    <option value="">Chọn quốc gia&hellip;</option>
    <option value="AF">Afghanistan</option>
    <option value="EG">Ai Cập</option>
    <option value="AL">Albania</option>
    <option value="DZ">Algeria</option>
    <option value="AS">American Samoa</option>
    <option value="AD">Andorra</option>
    <option value="AO">Angola</option>
    <option value="AI">Anguilla</option>
    <option value="GB">Anh (UK)</option>
    <option value="AQ">Antarctica</option>
    <option value="AG">Antigua và Barbuda</option>
    <option value="AR">Argentina</option>
    <option value="AM">Armenia</option>
    <option value="AW">Aruba</option>
    <option value="AZ">Azerbaijan</option>
    <option value="BS">Bahamas</option>
    <option value="BH">Bahrain</option>
    <option value="BD">Bangladesh</option>
    <option value="BB">Barbados</option>
    <option value="BY">Belarus</option>
    <option value="PW">Belau</option>
    <option value="BZ">Belize</option>
    <option value="BJ">Benin</option>
    <option value="BM">Bermuda</option>
    <option value="BT">Bhutan</option>
    <option value="BO">Bolivia</option>
    <option value="BQ">Bonaire, Saint Eustatius và Saba</option>
    <option value="BA">Bosnia và Herzegovina</option>
    <option value="BW">Botswana</option>
    <option value="BR">Brazil</option>
    <option value="BN">Brunei</option>
    <option value="BG">Bulgaria</option>
    <option value="BF">Burkina Faso</option>
    <option value="BI">Burundi</option>
    <option value="BE">Bỉ</option>
    <option value="PT">Bồ Đào Nha</option>
    <option value="CI">Bờ biển Ngà</option>
    <option value="CM">Cameroon</option>
    <option value="KH">Campuchia</option>
    <option value="CA">Canada</option>
    <option value="CV">Cape Verde</option>
    <option value="TD">Chad</option>
    <option value="CL">Chile</option>
    <option value="CX">Christmas Island</option>
    <option value="CO">Colombia</option>
    <option value="KM">Comoros</option>
    <option value="CG">Congo (Brazzaville)</option>
    <option value="CD">Congo (Kinshasa)</option>
    <option value="CR">Costa Rica</option>
    <option value="HR">Croatia</option>
    <option value="CU">Cuba</option>
    <option value="CW">Cura&Ccedil;ao</option>
    <option value="CY">Cyprus</option>
    <option value="UM">Các Tiểu đảo xa của Hoa Kỳ (US)</option>
    <option value="AE">Các tiểu vương quốc Ả Rập</option>
    <option value="DO">Cộng hòa Dominica</option>
    <option value="CZ">Cộng hòa Séc</option>
    <option value="CF">Cộng hòa Trung Phi</option>
    <option value="DJ">Djibouti</option>
    <option value="DM">Dominica</option>
    <option value="EC">Ecuador</option>
    <option value="SV">El Salvador</option>
    <option value="ER">Eritrea</option>
    <option value="EE">Estonia</option>
    <option value="ET">Ethiopia</option>
    <option value="FJ">Fiji</option>
    <option value="GA">Gabon</option>
    <option value="GM">Gambia</option>
    <option value="GE">Georgia</option>
    <option value="GH">Ghana</option>
    <option value="GI">Gibraltar</option>
    <option value="GL">Greenland</option>
    <option value="GD">Grenada</option>
    <option value="GP">Guadeloupe</option>
    <option value="GU">Guam</option>
    <option value="GT">Guatemala</option>
    <option value="GG">Guernsey</option>
    <option value="GN">Guinea</option>
    <option value="GQ">Guinea Xích đạo</option>
    <option value="GW">Guinea-Bissau</option>
    <option value="GY">Guyana</option>
    <option value="GF">Guyane thuộc Pháp</option>
    <option value="HT">Haiti</option>
    <option value="HN">Honduras</option>
    <option value="HU">Hungary</option>
    <option value="GR">Hy Lạp</option>
    <option value="NL">Hà Lan</option>
    <option value="KR">Hàn Quốc</option>
    <option value="HK">Hồng Kông</option>
    <option value="IS">Iceland</option>
    <option value="ID">Indonesia</option>
    <option value="IR">Iran</option>
    <option value="IQ">Iraq</option>
    <option value="IE">Ireland</option>
    <option value="IL">Israel</option>
    <option value="JM">Jamaica</option>
    <option value="JE">Jersey</option>
    <option value="JO">Jordan</option>
    <option value="KZ">Kazakhstan</option>
    <option value="KE">Kenya</option>
    <option value="KI">Kiribati</option>
    <option value="KW">Kuwait</option>
    <option value="KG">Kyrgyzstan</option>
    <option value="LV">Latvia</option>
    <option value="LB">Lebanon</option>
    <option value="LS">Lesotho</option>
    <option value="LR">Liberia</option>
    <option value="LY">Libya</option>
    <option value="LI">Liechtenstein</option>
    <option value="LT">Lithuania</option>
    <option value="LU">Luxembourg</option>
    <option value="LA">Lào</option>
    <option value="TF">Lãnh thổ miền Nam nước Pháp</option>
    <option value="IO">Lãnh thổ Ấn Độ Dương thuộc Anh</option>
    <option value="MO">Ma Cao</option>
    <option value="MK">Macedonia</option>
    <option value="MG">Madagascar</option>
    <option value="MW">Malawi</option>
    <option value="MY">Malaysia</option>
    <option value="MV">Maldives</option>
    <option value="ML">Mali</option>
    <option value="MT">Malta</option>
    <option value="MQ">Martinique</option>
    <option value="MR">Mauritania</option>
    <option value="MU">Mauritius</option>
    <option value="YT">Mayotte</option>
    <option value="MX">Mexico</option>
    <option value="FM">Micronesia</option>
    <option value="MD">Moldova</option>
    <option value="MC">Monaco</option>
    <option value="ME">Montenegro</option>
    <option value="MS">Montserrat</option>
    <option value="MA">Morocco</option>
    <option value="MZ">Mozambique</option>
    <option value="MM">Myanmar</option>
    <option value="MN">Mông Cổ</option>
    <option value="US">Mỹ (US)</option>
    <option value="NO">Na Uy</option>
    <option value="GS">Nam Georgia và Quần đảo Nam Sandwich</option>
    <option value="ZA">Nam Phi</option>
    <option value="SS">Nam Sudan</option>
    <option value="NA">Namibia</option>
    <option value="NR">Nauru</option>
    <option value="NP">Nepal</option>
    <option value="NC">New Caledonia</option>
    <option value="NZ">New Zealand</option>
    <option value="RU">Nga</option>
    <option value="JP">Nhật Bản</option>
    <option value="NI">Nicaragua</option>
    <option value="NE">Niger</option>
    <option value="NG">Nigeria</option>
    <option value="NU">Niue</option>
    <option value="NF">Norfolk Island</option>
    <option value="OM">Oman</option>
    <option value="PK">Pakistan</option>
    <option value="PS">Palestinian Territory</option>
    <option value="PA">Panama</option>
    <option value="PG">Papua New Guinea</option>
    <option value="PY">Paraguay</option>
    <option value="PE">Peru</option>
    <option value="PH">Philippines</option>
    <option value="FR">Pháp</option>
    <option value="PL">Phần Lan</option>
    <option value="FI">Phần Lan</option>
    <option value="PN">Pitcairn</option>
    <option value="PF">Polynesia thuộc Pháp</option>
    <option value="PR">Puerto Rico</option>
    <option value="QA">Qatar</option>
    <option value="AX">Quần đảo &#197;land</option>
    <option value="VG">Quần đảo British Virgin</option>
    <option value="MP">Quần đảo Bắc Mariana</option>
    <option value="KY">Quần đảo Cayman</option>
    <option value="CC">Quần đảo Cocos (Keeling)</option>
    <option value="CK">Quần đảo Cook</option>
    <option value="FK">Quần đảo Falkland</option>
    <option value="FO">Quần đảo Faroe</option>
    <option value="MH">Quần đảo Marshall</option>
    <option value="SB">Quần đảo Solomon</option>
    <option value="VI">Quần đảo Virgin của Hoa Kỳ (US)</option>
    <option value="RE">Reunion</option>
    <option value="RO">Romania</option>
    <option value="RW">Rwanda</option>
    <option value="ST">S&atilde;o Tom&eacute; và Pr&iacute;ncipe</option>
    <option value="BL">Saint Barth&eacute;lemy</option>
    <option value="SH">Saint Helena</option>
    <option value="KN">Saint Kitts và Nevis</option>
    <option value="LC">Saint Lucia</option>
    <option value="SX">Saint Martin (thuộc Hà Lan)</option>
    <option value="PM">Saint Pierre và Miquelon</option>
    <option value="VC">Saint Vincent và Grenadines</option>
    <option value="MF">Saint-Martin (thuộc Pháp)</option>
    <option value="SM">San Marino</option>
    <option value="SN">Senegal</option>
    <option value="RS">Serbia</option>
    <option value="SC">Seychelles</option>
    <option value="SL">Sierra Leone</option>
    <option value="SG">Singapore</option>
    <option value="SK">Slovakia</option>
    <option value="SI">Slovenia</option>
    <option value="SO">Somalia</option>
    <option value="LK">Sri Lanka</option>
    <option value="SD">Sudan</option>
    <option value="SR">Suriname</option>
    <option value="SJ">Svalbard và Jan Mayen</option>
    <option value="SZ">Swaziland</option>
    <option value="SY">Syria</option>
    <option value="TJ">Tajikistan</option>
    <option value="TZ">Tanzania</option>
    <option value="TH">Thái Lan</option>
    <option value="TR">Thổ Nhĩ Kỳ</option>
    <option value="CH">Thụy Sĩ</option>
    <option value="SE">Thụy Điển</option>
    <option value="TG">Togo</option>
    <option value="TK">Tokelau</option>
    <option value="TO">Tonga</option>
    <option value="TT">Trinidad và Tobago</option>
    <option value="KP">Triều Tiên</option>
    <option value="CN">Trung Quốc</option>
    <option value="TN">Tunisia</option>
    <option value="TM">Turkmenistan</option>
    <option value="TC">Turks và quần đảo Caicos</option>
    <option value="TV">Tuvalu</option>
    <option value="ES">Tây Ban Nha</option>
    <option value="UG">Uganda</option>
    <option value="UA">Ukraine</option>
    <option value="UY">Uruguay</option>
    <option value="UZ">Uzbekistan</option>
    <option value="VU">Vanuatu</option>
    <option value="VA">Vatican</option>
    <option value="VE">Venezuela</option>
    <option value="VN" selected='selected'>Việt Nam</option>
    <option value="WF">Wallis và Futuna</option>
    <option value="EH">Western Sahara</option>
    <option value="YE">Yemen</option>
    <option value="ZM">Zambia</option>
    <option value="ZW">Zimbabwe</option>
    <option value="AT">Áo</option>
    <option value="AU">Úc</option>
    <option value="IT">Ý</option>
    <option value="DK">Đan Mạch</option>
    <option value="TW">Đài Loan</option>
    <option value="TL">Đông Timo</option>
    <option value="BV">Đảo Bouvet</option>
    <option value="HM">Đảo Heard và quần đảo McDonald</option>
    <option value="IM">Đảo Man</option>
    <option value="WS">Đảo Samoa</option>
    <option value="DE">Đức</option>
    <option value="SA">Ả Rập Saudi</option>
    <option value="IN">Ấn Độ</option>
</select>
